"""Added initial models

Revision ID: fffad635dda5
Revises: 
Create Date: 2023-12-07 21:51:17.318423

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fffad635dda5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'abilities',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('internal_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('internal_id'),
    )
    op.create_table(
        'pokemons',
        sa.Column('pokemon_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pokemon_id'),
    )
    op.create_table(
        'types',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('internal_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('internal_id'),
    )
    op.create_table(
        'pokemon_abilities',
        sa.Column('pokemon_id', sa.Integer(), nullable=False),
        sa.Column('ability_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ['ability_id'],
            ['abilities.id'],
        ),
        sa.ForeignKeyConstraint(
            ['pokemon_id'],
            ['pokemons.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'pokemon_types',
        sa.Column('pokemon_id', sa.Integer(), nullable=False),
        sa.Column('type_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ['pokemon_id'],
            ['pokemons.id'],
        ),
        sa.ForeignKeyConstraint(
            ['type_id'],
            ['types.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sprites',
        sa.Column('pokemon_id', sa.Integer(), nullable=False),
        sa.Column(
            'sprite_type',
            sa.Enum(
                'DEFAULT',
                'DREAM_WORLD',
                'HOME',
                'OFFICIAL_ARTWORK',
                name='spritetype',
            ),
            nullable=False,
        ),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['pokemon_id'],
            ['pokemons.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprites')
    op.drop_table('pokemon_types')
    op.drop_table('pokemon_abilities')
    op.drop_table('types')
    op.drop_table('pokemons')
    op.drop_table('abilities')
    # ### end Alembic commands ###
